#!/usr/bin/env python3
# embed_html.py - Embeds an HTML file as a C string
# Usage: python3 embed_html.py input.html output.cpp

import sys
import os

if len(sys.argv) != 3:
    print("Usage: embed_html.py input.html output.cpp")
    sys.exit(1)

input_file = sys.argv[1]
output_file = sys.argv[2]

with open(input_file, 'r', encoding='utf-8') as f:
    content = f.read()

# Build a safe C symbol name from filename: index.html -> index_html
basename = os.path.basename(input_file)
symbol = "data_web_" + basename.replace('.', '_').replace('-', '_')

with open(output_file, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by embed_html.py - do not edit\n')
    f.write('extern "C" {\n\n')
    f.write('const char _binary_{}_start[] =\n'.format(symbol))
    
    # Write content line by line as string literals
    lines = content.split('\n')
    for i, line in enumerate(lines):
        escaped = line.replace('\\', '\\\\').replace('"', '\\"')
        if i < len(lines) - 1:
            f.write('  "{}\\n"\n'.format(escaped))
        else:
            if escaped:
                f.write('  "{}"\n'.format(escaped))
    
    f.write(';\n\n')
    f.write('const char _binary_{}_end[] = "";\n\n'.format(symbol))
    f.write('} // extern "C"\n')

print("Embedded {} -> {}".format(input_file, output_file))
